# -*- coding: utf-8 -*-
"""SHAK Working File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvyg7g6mKBZRvS-MMWamyvyHbVj4gP0r
"""

#Raw File before Streamlit focus

!pip install pandas requests

import pandas as pd
import requests

"""Building out the Model"""

# I am loading data about populations from the census API
# --- ACS 2023 state-level population + median income ---

BASE_ACS = "https://api.census.gov/data/2023/acs/acs1"

acs_vars = ["NAME", "B01003_001E", "B19013_001E"]  # state name, population, median income

acs_params = {
    "get": ",".join(acs_vars),
    "for": "state:*"
}

resp_acs = requests.get(BASE_ACS, params=acs_params)
resp_acs.raise_for_status()

data_acs = resp_acs.json()
df_acs = pd.DataFrame(data_acs[1:], columns=data_acs[0])

# Clean / rename
# Rename the FIPS 'state' column first to avoid conflict, then rename others
df_acs = df_acs.rename(columns={df_acs.columns[-1]: "state_fips"})
df_acs = df_acs.rename(columns={
    "NAME": "state",
    "B01003_001E": "population",
    "B19013_001E": "median_income"
})

df_acs["population"] = df_acs["population"].astype(int)
df_acs["median_income"] = df_acs["median_income"].astype(int)

# --- Add land area + pop density ---
area_url = "https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv"
area_df = pd.read_csv(area_url)  # columns: state, area (sq. mi)

df_acs = df_acs.merge(area_df, on="state", how="left")
df_acs["pop_density"] = df_acs["population"] / df_acs["area (sq. mi)"]

# --- Add state abbreviations ---
abbr_url = "https://raw.githubusercontent.com/jasonong/List-of-US-States/master/states.csv"
abbr_df = pd.read_csv(abbr_url)  # columns: state, Abbreviation

df_acs = df_acs.merge(abbr_df, left_on="state", right_on="State", how="left")
df_acs = df_acs.rename(columns={"Abbreviation": "state_abbrev"})

df_acs.head()

# --- CBP 2022: limited-service restaurants (NAICS 7225) by state ---

BASE_CBP = "https://api.census.gov/data/2022/cbp"

cbp_params = {
    "get": "ESTAB,NAME,NAICS2017",
    "for": "state:*",
    "NAICS2017": "7225",
}

resp_cbp = requests.get(BASE_CBP, params=cbp_params)
resp_cbp.raise_for_status()

data_cbp = resp_cbp.json()
df_cbp = pd.DataFrame(data_cbp[1:], columns=data_cbp[0])

# Rename the FIPS 'state' column first to avoid conflict with 'NAME' column
df_cbp = df_cbp.rename(columns={df_cbp.columns[-1]: "state_fips_cbp"})

df_cbp = df_cbp.rename(columns={
    "NAME": "state",
    "ESTAB": "qsr_establishments"
})
df_cbp["qsr_establishments"] = df_cbp["qsr_establishments"].astype(int)

df_cbp = df_cbp[["state", "qsr_establishments"]]

df_cbp.head()

# I uploaded the amount of stores from the 10k by what state they are located in
# --- Load SHAK state file you uploaded ---
shak = pd.read_csv("shak_state_locations_2024.csv")

# Rename 'State' to 'state' in shak to match df_acs
shak = shak.rename(columns={"State": "state"})

# Rename 'Total' to 'current_company_shacks' for later calculations
shak = shak.rename(columns={"Total": "current_company_shacks"})

# Merge shak with abbr_df to get 'state_abbrev'
# abbr_df was created in cell _qg47Kiy4uyT and has columns 'State' and 'Abbreviation'
shak = shak.merge(abbr_df, left_on="state", right_on="State", how="left")
shak = shak.rename(columns={"Abbreviation": "state_abbrev"})
# Drop the redundant 'State' column from abbr_df that was added during the merge
shak = shak.drop(columns=["State"]) # Drop 'State' as it's the column from abbr_df, not 'State_y'

# Check shapes
print("SHAK:", shak.shape)
print("ACS:", df_acs.shape)
print("CBP:", df_cbp.shape)

# Merge SHAK + ACS
# Now shak has 'state' and 'state_abbrev' for a successful merge
df = shak.merge(df_acs, on=["state", "state_abbrev"], how="inner")

# Merge QSR (competition)
df = df.merge(df_cbp, on="state", how="left")

# Competition per 100k residents
df["qsr_per_100k"] = df["qsr_establishments"] / (df["population"] / 100_000)

#  Core penetration metric
df["shacks_per_million"] = df["current_company_shacks"] / (df["population"] / 1_000_000)

df.head(5)

#How to get to 1500 units
# Choose "mature" benchmark states for density
mature_states = ["New York", "New Jersey"]

mature = df[df["state"].isin(mature_states)]
mature_density = mature["shacks_per_million"].mean()

# Conservative target_density: 70% of mature
target_density = 0.7 * mature_density
print("Mature density:", mature_density, "Target density:", target_density)

# Baseline potential units based on target density
df["potential_shacks_density"] = (df["population"] / 1_000_000) * target_density

# --- Build a demand score: income + density - QSR competition ---

# Normalize features
df["income_z"] = (df["median_income"] - df["median_income"].mean()) / df["median_income"].std()
df["density_z"] = (df["pop_density"] - df["pop_density"].mean()) / df["pop_density"].std()
df["qsr_z"] = (df["qsr_per_100k"] - df["qsr_per_100k"].mean()) / df["qsr_per_100k"].std()

# Demand score: higher income & density are good, higher QSR density is bad
df["demand_score"] = (
    0.5 * df["income_z"] +
    0.3 * df["density_z"] -
    0.2 * df["qsr_z"]
)

# Convert demand_score into multiplier (~0.7x to 1.3x)
df["demand_multiplier"] = 1 + 0.15 * df["demand_score"].clip(-2, 2)

# Final potential at maturity
df["potential_shacks"] = df["potential_shacks_density"] * df["demand_multiplier"]

import pandas as pd
import plotly.express as px

# Raw Demand Scores
top_n = 20
df_demand = df.sort_values("demand_score", ascending=False).head(top_n)

fig = px.bar(
    df_demand,
    x="state",
    y="demand_score",
    title=f"Demand Score by State (Top {top_n})",
    text="demand_score",
    labels={"state": "State", "demand_score": "Demand Score (z-score composite)"},
)

# Format labels (show to 2 decimal places, above bars)
fig.update_traces(
    texttemplate="%{text:.2f}",
    textposition="outside",
    marker_color="#005030"
)

fig.update_layout(
    xaxis_title="State",
    yaxis_title="Demand Score",
    title_x=0.5,
    bargap=0.2,
    uniformtext_minsize=9,
    uniformtext_mode="hide"
)

fig.show()

# White space = potential - current
df["white_space"] = (df["potential_shacks"] - df["current_company_shacks"]).clip(lower=0)

current_total = int(df["current_company_shacks"].sum())
target_total = 1500
incremental_needed = max(target_total - current_total, 0)

print("Current total company-operated:", current_total)
print("Incremental needed:", incremental_needed)

if incremental_needed > 0 and df["white_space"].sum() > 0:
    df["white_space_share"] = df["white_space"] / df["white_space"].sum()
    df["recommended_adds"] = (df["white_space_share"] * incremental_needed).round()
else:
    df["white_space_share"] = 0
    df["recommended_adds"] = 0

df["recommended_total"] = df["current_company_shacks"] + df["recommended_adds"]

# Sort for sanity check
df = df.sort_values("recommended_adds", ascending=False)

df.head(51)

import pandas as pd
import plotly.graph_objects as go

# PREP DATA

df_map = df.copy()
df_map["recommended_adds"] = df_map["recommended_adds"].round(0).astype(int)
df_map["hover_label"] = (
    df_map["state"] + "<br>"
    "Recommended Adds: " + df_map["recommended_adds"].astype(str)
)

# STATE CENTROIDS
state_centroids = {
    "AL": (32.8, -86.6), "AK": (63.0, -150.0), "AZ": (34.2, -111.6),
    "AR": (34.9, -92.4), "CA": (37.1, -120.4), "CO": (39.0, -105.5),
    "CT": (41.6, -72.7), "DE": (39.0, -75.5), "FL": (28.1, -82.5),
    "GA": (32.7, -83.2), "HI": (20.8, -157.5), "ID": (44.2, -114.4),
    "IL": (40.0, -89.2), "IN": (40.3, -86.1), "IA": (42.0, -93.2),
    "KS": (38.5, -98.3), "KY": (37.6, -85.3), "LA": (31.0, -92.0),
    "ME": (45.3, -69.0), "MD": (39.0, -76.7), "MA": (42.2, -71.8),
    "MI": (44.2, -85.4), "MN": (46.1, -94.3), "MS": (32.7, -89.7),
    "MO": (38.5, -92.5), "MT": (47.0, -109.6), "NE": (41.5, -99.7),
    "NV": (39.0, -116.8), "NH": (43.7, -71.6), "NJ": (40.1, -74.7),
    "NM": (34.3, -106.0), "NY": (42.9, -75.5), "NC": (35.5, -79.5),
    "ND": (47.5, -100.5), "OH": (40.3, -82.8), "OK": (35.6, -97.5),
    "OR": (44.0, -120.5), "PA": (40.9, -77.8), "RI": (41.7, -71.6),
    "SC": (33.8, -80.9), "SD": (44.3, -100.2), "TN": (35.8, -86.4),
    "TX": (31.0, -99.0), "UT": (39.3, -111.7), "VT": (44.1, -72.7),
    "VA": (37.5, -78.8), "WA": (47.5, -120.5), "WV": (38.6, -80.6),
    "WI": (44.6, -89.4), "WY": (43.1, -107.6),
    "DC": (38.9, -77.0)
}

df_map["lat"] = df_map["state_abbrev"].map(lambda x: state_centroids[x][0])
df_map["lon"] = df_map["state_abbrev"].map(lambda x: state_centroids[x][1])


# LABELS

df_labels = df_map[df_map["recommended_adds"] > 0].copy()
df_labels["lat_label"] = df_labels["lat"]
df_labels["lon_label"] = df_labels["lon"]


# BUILD FIGURE

fig = go.Figure()

# Choropleth with full outlines + readable Shake Shack colors
fig.add_trace(
    go.Choropleth(
        locations=df_map["state_abbrev"],
        z=df_map["recommended_adds"],
        locationmode="USA-states",

        colorscale=[
            [0.0, "#E8F6E8"],
            [0.3, "#A8D8A0"],
            [0.6, "#64B67A"],
            [1.0, "#2E8B57"]
        ],

        colorbar=dict(
            title="Recommended Adds",
            x=1.03,
            len=0.8
        ),

        marker_line_color="black",
        marker_line_width=0.7,

        customdata=df_map["hover_label"],
        hovertemplate="%{customdata}<extra></extra>"
    )
)

# Data labels at exact centroids
fig.add_trace(
    go.Scattergeo(
        lon=df_labels["lon_label"],
        lat=df_labels["lat_label"],
        text=df_labels["recommended_adds"],
        mode="text",
        textfont=dict(size=12, color="black"),
        showlegend=False
    )
)

fig.update_geos(
    scope="usa",
    projection_type="albers usa",
    showland=True,
    landcolor="white",
    showlakes=True,
    lakecolor="lightgray"
)

fig.update_layout(
    title="Recommended Net New Shake Shack Units — U.S. Map",
    title_x=0.5,
    margin=dict(l=20, r=120, t=60, b=20)
)

fig.show()

"""Chart Creation to show key areas of expansion"""

import plotly.express as px

# Top 10 states by recommended adds
top10 = df.sort_values("recommended_adds", ascending=False).head(10)

fig = px.bar(
    top10,
    x="state",
    y="recommended_adds",
    text="recommended_adds",
    title="White Space by State (Top 10)",
    labels={"recommended_adds": "Recommended New Company-Owned Shacks"},
)

# Format text labels (appear above bars)
fig.update_traces(
    texttemplate="%{text:.0f}",
    textposition="outside",
    marker_color="#005030"
)

fig.update_layout(
    xaxis_title="State",
    yaxis_title="Recommended Adds",
    title_x=0.5,
    bargap=0.15,
    uniformtext_minsize=10,
    uniformtext_mode="hide"
)

fig.show()

import pandas as pd
import plotly.graph_objects as go

# 1. Build the recommendation table
data = {
    "state": [
        "Texas",
        "California",
        "Florida",
        "Ohio",
        "Georgia",
        "Illinois",
        "North Carolina",
        "Michigan",
        "Washington",
        "Arizona"
    ],
    "state_abbrev": [
        "TX", "CA", "FL", "OH", "GA", "IL", "NC", "MI", "WA", "AZ"
    ],

    "low_rec":  [120, 100,  90,  40,  35,  35,  30,  30,  25,  25],
    "high_rec": [150, 130, 110,  55,  50,  50,  45,  45,  35,  35]
}

df_rec = pd.DataFrame(data)

# Midpoint for coloring
df_rec["mid_rec"] = (df_rec["low_rec"] + df_rec["high_rec"]) / 2

# Label text for data labels
df_rec["label"] = (
    df_rec["state_abbrev"]
    + ": "
    + df_rec["low_rec"].astype(str)
    + "–"
    + df_rec["high_rec"].astype(str)
)

# 2. Approx lat/lon for label placement
#    (rough state centers)
state_coords = {
    "TX": (31.0,  -99.0),
    "CA": (37.0, -120.0),
    "FL": (28.0,  -82.0),
    "OH": (40.4,  -82.8),
    "GA": (32.5,  -83.5),
    "IL": (40.0,  -89.0),
    "NC": (35.5,  -79.5),
    "MI": (44.3,  -85.5),
    "WA": (47.5, -120.5),
    "AZ": (34.2, -111.7)
}

df_rec["lat"] = df_rec["state_abbrev"].map(lambda s: state_coords[s][0])
df_rec["lon"] = df_rec["state_abbrev"].map(lambda s: state_coords[s][1])


# 3. Build the choropleth + text labels
fig = go.Figure()

shake_shack_green = [
    [0.0, "#e5f5e0"],   # very light green
    [0.5, "#7AB800"],   # Shack mid-green
    [1.0, "#005030"]    # deep Shack green
]

fig.add_trace(
    go.Choropleth(
        locations=df_rec["state_abbrev"],
        z=df_rec["mid_rec"],
        locationmode="USA-states",
        colorscale=shake_shack_green,
        colorbar=dict(
            title="Net New Units (midpoint)",
            x=1.04,     # push colorbar to the right so it doesn’t overlap labels
            xanchor="left",
            len=0.75
        ),
        customdata=df_rec[["state", "low_rec", "high_rec"]],
        hovertemplate=(
            "%{customdata[0]}<br>"
            "Recommended net new units: %{customdata[1]}–%{customdata[2]}<extra></extra>"
        ),
        name="Recommended Adds",
        marker_line_color="white",
        marker_line_width=0.5
    )
)

fig.add_trace(
    go.Scattergeo(
        locationmode="USA-states",
        lon=df_rec["lon"],
        lat=df_rec["lat"],
        text=df_rec["label"],
        mode="text",
        textfont=dict(size=10, color="black"),
        showlegend=False
    )
)

fig.update_geos(
    scope="usa",
    projection_type="albers usa",
    showland=True,
    landcolor="white",
    showcountries=False,
    showlakes=True,
    lakecolor="rgb(240, 240, 240)"
)

fig.update_layout(
    title_text="Recommended New Company-Owned Shake Shack Units by State: Top 10",
    title_x=0.5,
    margin=dict(l=20, r=90, t=60, b=20)
)

fig.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots


shack_colorscale = [
    [0.0, "#1b7837"],
    [0.5, "#ffffff"],
    [1.0, "#d73027"]
]

qsr_colorscale = [
    [0.0, "#1b7837"],
    [0.5, "#ffffff"],
    [1.0, "#d73027"]
]


fig = make_subplots(
    rows=1, cols=2,
    specs=[[{"type": "choropleth"}, {"type": "choropleth"}]],
    subplot_titles=[
        "<span style='font-size:16px;'>Shake Shack Penetration<br>(Shacks per 1M Residents)</span>",
        "<span style='font-size:16px;'>QSR Competition<br>(Restaurants per 100k Residents)</span>"
    ],
    horizontal_spacing=0.12
)

# LEFT MAP — SHAK Penetration
fig.add_trace(
    go.Choropleth(
        locations=df["state_abbrev"],
        z=df["shacks_per_million"],
        locationmode="USA-states",
        colorscale=shack_colorscale,
        zmin=0, zmax=4,
        colorbar=dict(
            title="Shacks / 1M",
            x=0.46,
            len=0.65
        ),
        hovertext=df["state"],
        hovertemplate="<b>%{hovertext}</b><br>Shacks per 1M: %{z:.2f}<extra></extra>",
        name="SHAK penetration"
    ),
    row=1, col=1
)

# RIGHT MAP — QSR Competition
fig.add_trace(
    go.Choropleth(
        locations=df["state_abbrev"],
        z=df["qsr_per_100k"],
        locationmode="USA-states",
        colorscale=qsr_colorscale,
        zmin=0, zmax=400,
        colorbar=dict(
            title="QSR / 100k",
            x=1.05,
            len=0.65
        ),
        hovertext=df["state"],
        hovertemplate="<b>%{hovertext}</b><br>QSR per 100k: %{z:.1f}<extra></extra>",
        name="QSR density"
    ),
    row=1, col=2
)

# GEOS
fig.update_geos(
    scope="usa",
    projection_type="albers usa",
    showlakes=True,
    lakecolor="white"
)

# Fix title overlap after running a few times
fig.update_layout(
    title_text="<b>Shake Shack Penetration vs QSR Competition (State-Level)</b>",
    title_x=0.5,
    title_y=0.97,
    margin=dict(l=0, r=40, t=110, b=0),
    font=dict(size=14),
)

# Assign traces to geos
fig.data[0].geo = "geo"
fig.data[1].geo = "geo2"

fig.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# PARAMETERS

start_year = 2025
end_year   = 2035
years = np.arange(start_year, end_year + 1)

# All scenarios start here (current company-owned units Q3 2025)
start_units = 359

# Year-over-year growth rates.
# Index 0 (2025) = 0% so all scenarios start at 359 and diverge from 2026 onward.

# Base case: "low-teens" growth that gently tapers due to diminishing over time
base_growth = np.array([
    0.00,  # 2025 (starting point)
    0.13,  # 2026
    0.13,  # 2027
    0.12,  # 2028
    0.12,  # 2029
    0.11,  # 2030
    0.11,  # 2031
    0.10,  # 2032
    0.10,  # 2033
    0.09,  # 2034
    0.09   # 2035
])

# Bull case: higher growth (mid-to-high teens early, then taper)
bull_growth = np.array([
    0.00,  # 2025
    0.18,  # 2026
    0.18,  # 2027
    0.17,  # 2028
    0.16,  # 2029
    0.15,  # 2030
    0.14,  # 2031
    0.13,  # 2032
    0.12,  # 2033
    0.11,  # 2034
    0.10   # 2035
])

# Bear case: high single-digit
bear_growth = np.array([
    0.00,  # 2025
    0.08,  # 2026
    0.08,  # 2027
    0.075,  # 2028
    0.075,  # 2029
    0.07,  # 2030
    0.07,  # 2031
    0.067,  # 2032
    0.067,  # 2033
    0.063,  # 2034
    0.063   # 2035
])

assert len(base_growth) == len(years)
assert len(bull_growth) == len(years)
assert len(bear_growth) == len(years)

def build_path_from_growth(start_units, growth_rates):
    """
    Build units path where:
    - First year (2025) starts at start_units
    - Each subsequent year = prior year * (1 + growth_rate)
    """
    units = [start_units]
    for g in growth_rates[1:]:   # skip first 0.00
        units.append(units[-1] * (1 + g))
    return np.array(units)

base_units = build_path_from_growth(start_units, base_growth)
bull_units = build_path_from_growth(start_units, bull_growth)
bear_units = build_path_from_growth(start_units, bear_growth)

paths_df = pd.DataFrame({
    "year": years,
    "base_units": base_units.round(0).astype(int),
    "bull_units": bull_units.round(0).astype(int),
    "bear_units": bear_units.round(0).astype(int)
})
display(paths_df)

# PLOT

plt.figure(figsize=(11, 7))

# Colors (approximate brand tones)
shake_shack_green = "#7AB800"  # base
money_green       = "#00A86B"  # bull
bear_red          = "#CC0000"  # bear

# Plot lines
plt.plot(years, base_units, marker="o", color=shake_shack_green,
         label="Base (low-teens growth)")
plt.plot(years, bull_units, marker="o", color=money_green,
         label="Bull (higher growth)")
plt.plot(years, bear_units, marker="o", color=bear_red,
         label="Bear (slower growth)")

# Horizontal line at 1,500 (mgmt target)
plt.axhline(1500, linestyle="--", color="gray", linewidth=1)
plt.text(years[0] + 0.1, 1500 + 40,
         "Mgmt long-term target: 1,500 units",
         fontsize=9, color="gray")

# Y-AXIS SPACING
min_y = min(bear_units) - 100
max_y = max(bull_units) + 200
plt.ylim(min_y, max_y)

#  DATA LABELS (black, staggered to reduce overlap)

for x, y in zip(years, base_units):
    # slight left shift, modest vertical offset
    plt.text(x - 0.15, y + 30, f"{int(y)}",
             ha="center", va="bottom",
             fontsize=8, color="black")

for x, y in zip(years, bull_units):
    # no x-shift, bigger vertical offset
    plt.text(x, y + 60, f"{int(y)}",
             ha="center", va="bottom",
             fontsize=8, color="black")

for x, y in zip(years, bear_units):
    # slight right shift, downward offset
    plt.text(x + 0.15, y - 50, f"{int(y)}",
             ha="center", va="top",
             fontsize=8, color="black")

plt.title(
    "Scenario Paths to 1,500 Company-Owned Shake Shack Locations\n"
    "(all scenarios start at 359 units in 2025)"
)
plt.xlabel("Year")
plt.ylabel("Company-Owned Stores")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.4)


plt.tight_layout(rect=[0, 0.12, 1, 0.95])

# RATIONALE
note_text = (
    "Note: Base scenario assumes low-teens annual growth in company-owned units, "
    "with higher growth in the bull case and slower build-out in the bear case. "
    "Illustrative paths are broadly anchored on management's long-term unit growth "
    "framework discussed in the January investor presentation; they are not guidance."
)

plt.figtext(0.5, 0.03, note_text, wrap=True, ha="center", fontsize=8)

plt.show()

"""Comparison with other chains"""

#Compare other chains by size
import pandas as pd
import plotly.express as px

data = {
    "brand": [
        "Chipotle Mexican Grill",
        "Five Guys",
        "Shake Shack",
        "Smashburger",
        "BurgerFi"
    ],
    "total_locations": [3800, 1500, 539, 200, 93]
}

df_peers = pd.DataFrame(data)
df_peers = df_peers.sort_values("total_locations", ascending=False)

color_map = {
    "Chipotle Mexican Grill": "#7b3f00",
    "Five Guys": "#d52b1e",
    "Shake Shack": "#2cb34a",
    "Smashburger": "#e31b23",
    "BurgerFi": "#7ac143"
}

fig = px.bar(
    df_peers,
    x="brand",
    y="total_locations",
    title="Better-Burger / Fast-Casual Peer Comparison (Total Locations)",
    labels={"brand": "Brand", "total_locations": "Total Restaurants (Global/System)"},
    color="brand",
    color_discrete_map=color_map,
    text="total_locations"
)

# Add data labels above bars
fig.update_traces(
    textposition="outside",
    textfont=dict(size=14)
)


max_val = df_peers["total_locations"].max()
fig.update_yaxes(range=[0, max_val * 1.15])   #Preventing the data labels from clippiing the top of chart

fig.update_layout(
    xaxis_tickangle=-30,
    showlegend=False,
    yaxis=dict(title="Total Restaurants"),
    xaxis=dict(title="")
)
fig.add_annotation(
    text="*Smashburger and BurgerFi totals are approximate due to conflicting public data,\n"
         "but differences are marginal for the comparative analysis.",
    xref="paper",
    yref="paper",
    x=0,
    y=-0.35,
    showarrow=False,
    font=dict(size=12, color="gray"),
    align="left"
)

fig.update_layout(
    margin=dict(b=120),   # extra bottom margin so footnote fits
    xaxis_tickangle=-30,
    showlegend=False,
    yaxis=dict(title="Total Restaurants"),
    xaxis=dict(title="")
)

fig.show()

"""Margin checking"""

import pandas as pd
import plotly.express as px

# Competitive margin data
data = {
    "company": [
        "Chipotle Mexican Grill",
        "Shake Shack",
        "BurgerFi",
        "Smashburger"
    ],
    "restaurant_margin_pct": [
        26.7,   # Chipotle 2024 10-K
        21.4,   # Shake Shack 2024 10-K
        12.0,   # BurgerFi Quarterly
        9.0,    # Approx based on Jollibee disclosures

    ],
    "color": [
        "#8B0000",  # Chipotle red
        "#43A047",  # Shake Shack green
        "#000000",  # BurgerFi black
        "#D32F2F",  # Smashburger red

    ]
}

df_margins = pd.DataFrame(data)

# Sort DESC (target: Shake Shack highlighted)
df_margins_sorted = df_margins.sort_values(
    by="restaurant_margin_pct",
    ascending=False,
    na_position="last"
)

# Plot
fig = px.bar(
    df_margins_sorted,
    x="company",
    y="restaurant_margin_pct",
    title="Restaurant-Level Margins: Shake Shack vs Premium Fast-Casual Peers",
    text="restaurant_margin_pct",
    color="company",
    color_discrete_map={row.company: row.color for _, row in df_margins_sorted.iterrows()},
)

fig.update_traces(texttemplate="%{text}%", textposition="outside")
fig.update_layout(
    yaxis_title="Restaurant-Level Margin (%)",
    xaxis_title="Company",
    xaxis_tickangle=-30,
    plot_bgcolor="white"
)

fig.show()

import matplotlib.pyplot as plt

# Shake Shack restaurant-level margins from 10-Ks
years = [2022, 2023, 2024]
margins = [17.5, 19.9, 21.4]  # percentages


shake_shack_green = "#2E8B57"

plt.figure(figsize=(10, 6))

# Plot the line
plt.plot(years, margins, marker='o', linewidth=3, color=shake_shack_green)

# Add labels over data points
for x, y in zip(years, margins):
    plt.text(x, y + 0.3, f"{y}%", ha='center', fontsize=12)

# Title & axis labels
plt.title("Shake Shack Restaurant-Level Profit Margin (2022–2024)", fontsize=16)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Restaurant-Level Profit Margin (%)", fontsize=14)

# Enforce year-by-year (no half years)
plt.xticks(years)

# Clean grid
plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

import pandas as pd
import plotly.graph_objects as go

rev_data = pd.DataFrame({
    "year": [2020, 2021, 2022, 2023, 2024],
    "revenue": [523, 739, 900, 1098, 1310],
    "units": [183, 218, 263, 307, 329]
})

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=rev_data["year"],
        y=rev_data["revenue"],
        name="Revenue ($M)",
        marker_color="#005030"
    )
)

fig.add_trace(
    go.Scatter(
        x=rev_data["year"],
        y=rev_data["units"],
        name="Company-Operated Units",
        yaxis="y2",
        mode="lines+markers",
        marker_color="black"
    )
)

fig.update_layout(
    title="Revenue Growth vs. Store Count",
    title_x=0.5,
    yaxis=dict(title="Revenue ($M)"),


    yaxis2=dict(
        title="Units",
        overlaying="y",
        side="right",
        ticklabelposition="outside right",   # ← prevents overlap with legend
        tickfont=dict(color="black")
    ),

    # Increase right margin so the labels have room
    margin=dict(l=70, r=110, t=80, b=60),
    legend=dict(x=0.55, y=1.05)
)

fig.show()

fig = px.scatter(
    df,
    x="pop_density",
    y="shacks_per_million",
    text="state_abbrev",
    title="State-Level Penetration vs Population Density",
)

fig.update_traces(textposition="top center", marker_size=12, marker_color="#005030")
fig.update_layout(xaxis_title="Population Density", yaxis_title="Shacks per Million")

fig.show()

fig = px.scatter(
    df,
    x="qsr_per_100k",
    y="shacks_per_million",
    text="state_abbrev",
    title="SHAK Penetration vs QSR Competition",
)

fig.update_traces(marker_color="red", marker_size=12, textposition="top center")
fig.update_layout(xaxis_title="QSR per 100k Residents", yaxis_title="Shacks per Million")

fig.show()

import plotly.express as px
import pandas as pd



fig = px.scatter(
    df,
    x="qsr_per_100k",
    y="shacks_per_million",
    text="state_abbrev",
    trendline="ols",
    color="shacks_per_million",
    color_continuous_scale=["#1b7837", "#ffffff", "#d73027"],  # green → white → red
    title="Shake Shack Penetration vs. QSR Competitive Intensity"
)

fig.update_traces(
    textposition="top center",
    marker=dict(size=12, line=dict(width=1, color="black"))
)

fig.update_layout(
    xaxis_title="QSR Restaurants per 100k Residents",
    yaxis_title="Shacks per 1M Residents",
    title_x=0.5,
    plot_bgcolor="white",
    coloraxis_colorbar=dict(
        title="Shacks per 1M",
        ticks="outside"
    )
)

fig.show()

# Define the Top 10 States manually
top_10_states = ["TX", "CA", "FL", "OH", "GA", "IL", "NC", "MI", "WA", "AZ"]

# Create the missing 'category' column
df['category'] = df['state_abbrev'].apply(lambda x: 'Top 10 Target' if x in top_10_states else 'Other State')

# Create the missing 'region' column (needed for Chart 3)
region_map = {
    'Northeast': ['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA'],
    'Midwest': ['IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD'],
    'South': ['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX'],
    'West': ['AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA']
}
state_to_region = {state: region for region, states in region_map.items() for state in states}
df['region'] = df['state_abbrev'].map(state_to_region).fillna('Other')

print("Fix complete: 'category' and 'region' columns added.")

# Create Interactive Bubble Chart
fig_bubble = px.scatter(
    df,
    x="median_income",
    y="shacks_per_million",
    size="population",
    color="category",
    color_discrete_map={'Top 10 Target': '#005030', 'Other State': '#A8D8A0'},
    hover_name="state",
    text="state_abbrev",
    title="Penetration vs. Median Household Income",
    trendline="ols"
)

fig_bubble.update_traces(textposition='top center', marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig_bubble.update_layout(
    height=600,
    plot_bgcolor="white",
    xaxis=dict(gridcolor="lightgray", title="Median Household Income ($)"),
    yaxis=dict(gridcolor="lightgray", title="Current Shacks per 1M Residents"),
    legend=dict(orientation="h", y=1.05, x=0.5, xanchor="center")
)
fig_bubble.show()

top_potential = df.sort_values("potential_shacks", ascending=False).head(15)
fig_dumbbell = go.Figure()

# The Line
for i, row in top_potential.iterrows():
    fig_dumbbell.add_trace(go.Scatter(
        x=[row['current_company_shacks'], row['potential_shacks']],
        y=[row['state'], row['state']],
        mode='lines',
        line=dict(color='lightgray', width=3),
        showlegend=False,
        hoverinfo='skip'
    ))

# Dot: Current
fig_dumbbell.add_trace(go.Scatter(
    x=top_potential['current_company_shacks'], y=top_potential['state'],
    mode='markers', name='Current Units', marker=dict(color='#A8D8A0', size=12)
))

# Dot: Potential
fig_dumbbell.add_trace(go.Scatter(
    x=top_potential['potential_shacks'], y=top_potential['state'],
    mode='markers', name='Total Potential Capacity', marker=dict(color='#005030', size=16, symbol='diamond')
))

fig_dumbbell.update_layout(
    title="Top 15 States: Closing the Whitespace Gap",
    xaxis_title="Number of Shake Shack Units",
    yaxis=dict(autorange="reversed"),
    plot_bgcolor="white",
    legend=dict(orientation="h", y=1.1, x=0.5, xanchor="center"),
    height=600
)
fig_dumbbell.show()

region_group = df.groupby("region")[["recommended_adds", "current_company_shacks"]].sum().reset_index()

fig_donut = px.pie(
    region_group,
    values="recommended_adds",
    names="region",
    title="Share of Recommended New Units by Region",
    hole=0.5,
    color_discrete_sequence=["#005030", "#448D44", "#7AB800", "#C8E6C9"]
)
fig_donut.update_traces(textinfo='percent+label')
fig_donut.show()